name: pyladies_pls_intro
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.20.*
  - pandas=1.3.*
  - scikit-learn=1.0.*
  - matplotlib=3.4.*
  - ipykernel=6.2.*
  - pip
  - pip:
  - kaggle=1.5.*